#!/bin/bash

echo "********************************************************************"
echo "You should input the target username and password according the hint"
echo "********************************************************************"

echo ""
echo "now hit the enter key to continue..."

read enter

if [ -f ".ssh/id_rsa.pub" ];then
    echo "id_rsa.pub exists, jump the step"
else
    echo "you should hit the Enter key three times on A machine or set your arguments"
    ssh-keygen -t rsa
fi

echo "copying the id_rsa.pub to the target machine"
echo "now type the target machine name:(like amay@10.1.1.1)"

read target

#echo $target

#gen change exe filea
exefile=append_pub
touch $exefile
chmod 711 $exefile
echo "#!/bin/bash" >> $exefile
echo "cat id_rsa.pub >> .ssh/authorized_keys" >> $exefile
echo "chmod 600 .ssh/authorized_keys" >> $exefile
echo "rm id_rsa.pub $exefile" >> $exefile

echo "scp .ssh/id_rsa.pub $exefile $target:"

scp .ssh/id_rsa.pub $exefile $target:

ssh $target "cd ~/; ./$exefile"

if [ -f "genssh" ];then
    echo "genssh file exists in current dir"
    echo "scp genssh $target:"
    scp genssh $target:
else
    echo "genssh file not exists in current dir"
fi

rm $exefile
